spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/file
    username: postgres
    password: 1807
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 125MB
image:
  folder:
    path:
      src/main/resources/images/